### ISSUE TITLE
test failures under Strawberry Perl 5.36.1 (dev version)

### ISSUE THREAD

**Issue by shawnlaffan** [Grinnz/lib-relative#3]
As noted in https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/103, ```lib::relative``` is failing its symlink related tests.  

This particular Strawberry Perl dev release is built without symlink support.  

The logic to detect if symlinks are supported needs to be updated, possibly adapting from ```Path::Tiny```.
https://github.com/dagolden/Path-Tiny/blob/7a84e3c6952e8d27e3963c92e6087aac36534451/t/lib/TestUtils.pm#L26-L41

**Comment by Grinnz** [comment]
Fixed by #4 and released in 1.002. Thanks for the report
